package com.example.rxdemo.controller;

import com.example.rxdemo.dto.CreateUserRequest;
import com.example.rxdemo.dto.UserResponse;
import com.example.rxdemo.exceptions.EmailUniquenessException;
import com.example.rxdemo.model.User;
import com.example.rxdemo.repository.UserRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;


@RestController
@RequestMapping("/users")
public class UserController {

    private static final Logger log = LoggerFactory.getLogger(UserController.class);
    private final UserRepository userRepository;

    public UserController(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    // Mapping methods

    private User mapToEntity(CreateUserRequest request) {
        // ID is null because it will be generated by the database
        return new User(null, request.name(), request.email());
    }

    private UserResponse mapToResponse(User user) {
        return new UserResponse(user.id(), user.name(), user.email());
    }


    @PostMapping
    public Mono<ResponseEntity<UserResponse>> createUser(@RequestBody CreateUserRequest request) {
        User userToSave = mapToEntity(request); // Mapping DTO to entity
        return userRepository.findByEmail(userToSave.email())
                .flatMap(existingUser -> Mono.<User>error(new EmailUniquenessException("Email already exists!")))
                .switchIfEmpty(Mono.defer(() -> userRepository.save(userToSave)))
                .map(savedUser -> {
                    log.info("New user created: {}", savedUser); // Keep logging if desired, or move to service
                    return ResponseEntity.status(HttpStatus.CREATED).body(mapToResponse(savedUser)); // Return 201 CREATED
                });
        // No .onErrorResume here - let GlobalExceptionHandler handle it
    }

    @GetMapping
    public Flux<UserResponse> getAllUsers() {
        return userRepository.findAll()
                .map(this::mapToResponse); // Map each User entity to UserResponse
    }

    @GetMapping("/{id}")
    public Mono<UserResponse> getUserById(@PathVariable Long id) {
        return userRepository.findById(id)
                .map(this::mapToResponse); // Map the User entity to UserResponse
    }

    @DeleteMapping("/{id}")
    public Mono<Void> deleteUserById(@PathVariable Long id) {
        return userRepository.deleteById(id);
    }

    @GetMapping("/stream")
    public Flux<UserResponse> streamAllUsers() {
        long start = System.currentTimeMillis();
        return userRepository.findAll()
                .map(this::mapToResponse)
                .onBackpressureBuffer() // Buffer strategy for backpressure
                .doOnNext(userResp -> log.debug("Processed UserResponse: {} in {} ms ", userResp.name(), System.currentTimeMillis() - start))
                .doOnError(error -> log.error("Error streaming users", error))
                .doOnComplete(() -> log.info("Finished streaming users for streamUsers in {} ms", System.currentTimeMillis() - start));
    }

}
